from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors
import io
from datetime import datetime

def create_pdf_report(ref_image, suspect_image, results):
    """
    Generates a PDF forensic report.
    
    Args:
        ref_image (PIL.Image): Reference image.
        suspect_image (PIL.Image): Suspect image.
        results (dict): Verification results.
        
    Returns:
        bytes: PDF file content.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Header
    c.setFillColor(colors.black)
    c.rect(0, height - 100, width, 100, fill=1)
    
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 60, "AURA | FORENSIC ANALYSIS REPORT")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 80, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Verdict Section
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 150, "VERDICT:")
    
    verdict = results['verdict']
    color = colors.green if "AUTHENTIC" in verdict else colors.red
    c.setFillColor(color)
    c.drawString(150, height - 150, verdict)
    
    # Metrics
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 12)
    y = height - 200
    c.drawString(50, y, f"Confidence Score: {results['confidence']}%")
    c.drawString(50, y - 20, f"Similarity Distance: {results['similarity_score']} (Lower is better)")
    c.drawString(50, y - 40, f"Anomaly Score: {results['anomaly_score']} (Lower is better)")
    c.drawString(50, y - 60, f"Quantum Fidelity: {results['quantum_score']} (Higher is better)")
    
    # Images
    y_img = y - 250
    img_width = 200
    img_height = 200
    
    # Convert PIL images to ReportLab ImageReader
    # We need to save them to bytes first
    def pil_to_reader(img):
        b = io.BytesIO()
        img.save(b, format='JPEG')
        b.seek(0)
        return ImageReader(b)

    try:
        c.drawImage(pil_to_reader(ref_image), 50, y_img, width=img_width, height=img_height, preserveAspectRatio=True)
        c.drawString(50, y_img - 20, "Reference Artwork")
        
        c.drawImage(pil_to_reader(suspect_image), 300, y_img, width=img_width, height=img_height, preserveAspectRatio=True)
        c.drawString(300, y_img - 20, "Suspect Artwork")
    except Exception as e:
        c.drawString(50, y_img, f"Error rendering images: {e}")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(colors.gray)
    c.drawString(50, 50, "Generated by AURA Fake Art Verification Service. Powered by Deep Learning & Quantum Simulation.")
    
    c.save()
    buffer.seek(0)
    return buffer.getvalue()
